### ISSUE TITLE
Ben's thoughts

### ISSUE THREAD

**Issue by DukeBaird** [loewen-uwaterloo/my-website#1]
You're including the movie sorting js on every page - this seems excessive. if you dont use it, dont include it. If its truly a "global" js file, it shouldnt have single page specific js.

If you're loading the js at the end of the html file, you dont need $(document).ready either.

Your sidebar flickers, you can chain your css classes together to have them default to hidden on load.

You have a bunch of console errors on the movie listings page - its looking for images that arent there.
Also maybe some labels on the sliders, now that I know theyre for sorting. While im thinking about it, typing in the boxes and pressing enter doesnt adjust the sliders, but moving the slider adjusts the box. The poor box must feel excluded.

Why is your error log in your git repo?

You have a css file at the top of your project?

You have a lot of JQuery. Personally not a fan, but I understand the appeal.

Nice work on the templating, it looks good.

**Comment by bashlyss** [comment]
Thanks for the feedback.  May not need document.ready, but it's better habitually.

Thanks for pointing out the error log, I hadn't noticed it is all.  And I didn't realize there was css at the root either.  That will be remedied shortly.

**Comment by bashlyss** [comment]
commits
0331a4ff805729a474edf797340aaf4428691318
9fd53792fe0effd2fb7bc7e3a1a65122f541a8b2
Doesn't fix sliders.  Will create separate issue
